image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      ./mvnw package
      docker-compose pull
    command: |
      docker-compose up
      ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot

jetbrains:
  intellij:
    prebuilds:
      version: stable
