schematic:
  name: @project.name@
  version: @project.version@
  path: schematic
  root-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
